Update android.yml

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -1,30 +1,52 @@
 name: Android CI
-on: workflow_dispatch
+on:
+  push:
+    branches: [ "master" ]
 
 jobs:
   build:
 
     runs-on: ubuntu-latest
     steps:
-    - name: Hello
-      run: echo "HI All"
-    - name: Repo
-      run: echo $GITHUB_REPOSITORY
-  repo_name_job:
-    name: Deployed branch
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v2
+     - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v1
         with:
-          fetch-depth: 0
-          
-      
-          
-      - name: Show repository name
-        run: echo $GITHUB_REPOSITORY
-  
-      - name: Label Fixed Issues
-        uses: gh-bot/fix-labeler@master
-        with:
-          label: ''
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
+          aws-region: us-east-1
+    - name: Pull base vs-server image
+        run: |
+          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 906882710583.dkr.ecr.us-east-1.amazonaws.com
+          docker pull 906882710583.dkr.ecr.us-east-1.amazonaws.com/vs-server:1.0.0
+          docker logout
+      - name: Login to Amazon ECR
+        id: login-ecr
+        uses: aws-actions/amazon-ecr-login@v1
+
+      - name: Get repo name
+        id: extract-repo-name
+        shell: bash
+        run: |
+          repo_name="${GITHUB_REPOSITORY##*/}"
+          echo "PXLT_ECR_REPOSITORY=$repo_name" >> $GITHUB_ENV
+      - name: Find image in ECR
+        id: find-image-in-ecr
+        shell: bash
+        continue-on-error: true # This step will fail if image doesnt exist but will be marked as successful because of "continue-on-error"
+        run: |
+          response="$(aws ecr describe-images --repository-name=${PXLT_ECR_REPOSITORY} --image-ids=imageTag=${PXLT_COMMIT_HASH})"
+          if [[ $? == 0 ]]; then
+              echo "Docker image ${PXLT_ECR_REPOSITORY}:${PXLT_COMMIT_HASH} found in ECR"
+              echo "Skipping build image step"
+          fi
+      - name: Build, tag and push image to Amazon ECR
+        id: build-image
+        env:
+          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+        if: steps.find-image-in-ecr.outcome == 'failure'
+        run: |
+          docker build -t ${ECR_REGISTRY}/${PXLT_ECR_REPOSITORY}:${PXLT_IMAGE_TAG} -t ${ECR_REGISTRY}/${PXLT_ECR_REPOSITORY}:${PXLT_COMMIT_HASH} \
+            --build-arg RELEASE=$PXLT_IMAGE_TAG .
+          docker push ${ECR_REGISTRY}/${PXLT_ECR_REPOSITORY}:${PXLT_IMAGE_TAG}
+          docker push ${ECR_REGISTRY}/${PXLT_ECR_REPOSITORY}:${PXLT_COMMIT_HASH}
+          echo "::set-output name=image::${ECR_REGISTRY}/${PXLT_ECR_REPOSITORY}:${PXLT_IMAGE_TAG}"
